ALTER TABLE order_items ADD COLUMN IF NOT EXISTS size VARCHAR(20);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS number VARCHAR(50);
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS jersey_type VARCHAR(50);
